### ISSUE TITLE
Add repos query with user filter

### ISSUE THREAD

**Issue by hereisnaman** [hereisnaman/api.gitfa.me#23]
Add a query field repositories with filter for user.

```
repositories({where: { user: { username: <username>, uid: <uid> }}}) 
```

**Comment by kapillamba4** [comment]
@hereisnaman, i am unable to fetch repositories even after using github token with all scopes set for  dev server. [This line gives type-error](https://github.com/hereisnaman/api.gitfa.me/blob/1487cc42966b67b7aa6e358acb1e94dd56e334cd/app/actions/fetchRepo.js#L23) Can you please help me here?
![image](https://user-images.githubusercontent.com/20877996/40265335-ed97b9dc-5b53-11e8-984f-c3cb0d272c67.png)

**Comment by kapillamba4** [comment]
@hereisnaman Do you mean fetch all repositories a user is having for another user (forked) or fetch all source repositories for a user?

**Comment by 0xnmn** [comment]
@kapillamba4 yes or otherwise return all repos. Well you can limit it to have a required where argument.

**Comment by kapillamba4** [comment]
I can either add a field to actual graphql query to get all source repositories for user:
![image](https://user-images.githubusercontent.com/20877996/40268733-5c176286-5b90-11e8-9cdb-179e69a1dcc9.png)

Or i can either filter final response with username provided:
![image](https://user-images.githubusercontent.com/20877996/40269101-e67c6d1c-5b96-11e8-8d06-d91037ea1e71.png)


I don't think where field is supported by graphql github api

**Comment by 0xnmn** [comment]
@kapillamba4 what it has to do with github api? You have to create query fields for the app's api and to resolve have to use prisma bindings.

**Comment by kapillamba4** [comment]
@hereisnaman I meant ![this](https://github.com/hereisnaman/api.gitfa.me/blob/1487cc42966b67b7aa6e358acb1e94dd56e334cd/app/actions/payload.js#L55), sorry i have no experience in graphql or prisma. Just trying to understand the source code

**Comment by 0xnmn** [comment]
@kapillamba4 its okay, actually you have to add query fields in the app api, i.e. app/schema.graphql and corresponding resolver. I'll update the readme with the project structure soon. You'll need to know about grphql to solve this, what is better than learning it :).
